### ISSUE TITLE
Provide option to use command line Git instead of Cake.Git

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Issues.Recipe#183]
Cake.Git addin, which uses LibGit2Sharp, can have issues on certain environments. There should be an option which allows to use Cake.Issues.Recipe without Cake.Git but calls to Git command line instead.

**Comment by nils-a** [comment]
Wouldn't it be more prudent to create a `Cake.GitClient`, which does not rely on LibGit2Sharp but rather on an existing git command line client.
Those "problems" of LibGit2Sharp are inherent to more systems than Cake.Issues.Recipe, right?

**Comment by pascalberger** [comment]
Yes, thought about this. What would be nice is to have an abstraction layer, which is then either implemented using LibGit2Sharp or by calling the command line client. If done across multiple addins, this would mean that we need a Cake.GitInterface addin, defining the interface and one addin implementing the interface for LibGit2Sharp and one for command line client. In the build you then would need to add the interface addin plus one of the implementation addins and register it. This is basically how extensibility is also handled in Cake.Issues, but in this case it probably would be easier to handle all this in a single addin which provides both possibilities.

**Comment by pascalberger** [comment]
Created issue in https://github.com/cake-contrib/Cake_Git/issues/146 for discussing this further

**Comment by pascalberger** [comment]
For the time being, I decided to add an option to Cake.Issues recipe, which can be used to decide it Cake.Git or Git CLI should be used, as there are only 3 calls which are required.
