### ISSUE TITLE
Can't use Cake 2.0.0 due to dependency chain of Cake.Frosting.Issues.Recipe 1.3.2

### ISSUE THREAD

**Issue by donker** [cake-contrib/Cake.Issues.Recipe#253]
We use Cake.Frosting.Issues.Recipe 1.3.2 and with VS 2022 need to update to Cake 2.0.0. But we're getting stuck as we also rely on Cake.Frosting.Issues.Recipe which in its chain doesn't accept Cake 2.0.0.

**Comment by pascalberger** [comment]
Official support for Cake 2.x will come with Cake.Issues 2.0. In the meantime I'll release a version of Cake.Frosting.Issues.Recipe which contains a version of Cake.Frosting.Issues.Reporting.Generic which is still built against Cake 1.0 but is not restrict to be used with Cake 1.x only.

**Comment by bdukes** [comment]
Thanks! Is there an issue we can watch that's tracking Cake.Issues 2.0?

**Comment by pascalberger** [comment]
There are issues for the different Cake.Issues addins. For some there are already 2.0 Beta versions available. If you want to track Cake.Issues.Recipe #256 would be the issue.

**Comment by pascalberger** [comment]
Fixed with #257

**Comment by pascalberger** [comment]
@bdukes Version 1.3.3 of Cake.Frosting.Issues.Recipe is now available which no longer restricts dependencies to Cake 1.x. 

Please note that While this makes it possible from a technical point of view to use it with Cake 2.x, all addins in this version are still built against Cake 1.0 and there might be cases where it fails when running on Cake 2.x (I haven't experienced any yet)

**Comment by bdukes** [comment]
Thanks so much, we appreciate it!
